avalanche:
  rpc_url: "https://api.avax.network/ext/bc/C/rpc"  # Update with the correct RPC URL
  router_abi: "router_abi.json"  # Assuming you have this ABI for your specific router
  erc20_abi: "erc20_abi.json"
  erc721_abi: "erc721_abi.json"
